### ISSUE TITLE
grant_type error message when authenticating

### ISSUE THREAD

**Issue by halomakes** [huoyaoyuan/pixiv-api-client#2]
Hello,
I'm replacing the discontinued pixiv api client used in my chat bot with this and am getting an error when trying to call AuthAsync with a user ID and password.

```csharp
var (authTime, authResponse) = await pixiv.AuthAsync(pixivConfig.UserId, pixivConfig.Password);
return await pixiv.SearchIllustsAsync(authToken: authResponse.AccessToken, word: query);
```
```
17:02:47 <CbTest> Encountered PixivAuthException from Meowtrix.PixivApi
17:02:47 <CbTest> Base PixivAuthException: Invalid grant_type parameter or parameter missing
17:02:47 <CbTest>    at Meowtrix.PixivApi.PixivApiClient.AuthAsync(HttpRequestMessage request, CancellationToken cancellationToken)
17:02:47 <CbTest>    at Meowtrix.PixivApi.PixivApiClient.AuthAsync(String username, String password, CancellationToken cancellationToken)
17:02:47 <CbTest>    at ChatBeet.Commands.PixivCommandProcessor.<>c__DisplayClass4_0.<<RespondAsync>b__1>d.MoveNext() in C:\Users\Alex\Code\ChatBeet\ChatBeet\Commands\PixivCommandProcessor.cs:line 41
17:02:47 <CbTest> --- End of stack trace from previous location ---
17:02:47 <CbTest>    at Microsoft.Extensions.Caching.Memory.CacheExtensions.GetOrCreateAsync[TItem](IMemoryCache cache, Object key, Func`2 factory)
17:02:47 <CbTest>    at ChatBeet.Commands.PixivCommandProcessor.RespondAsync(String query) in C:\Users\Alex\Code\ChatBeet\ChatBeet\Commands\PixivCommandProcessor.cs:line 37
17:02:47 <CbTest>    at GravyBot.Commands.CommandOrchestratorRule.RespondAsync(PrivateMessage incomingMessage)+MoveNext()
17:02:47 <CbTest>    at GravyBot.Commands.CommandOrchestratorRule.RespondAsync(PrivateMessage incomingMessage)+System.Threading.Tasks.Sources.IValueTaskSource<System.Boolean>.GetResult()
17:02:47 <CbTest>    at GravyBot.MessageQueueService.<>c__DisplayClass12_0`1.<<ApplyRules>g__ExecuteRuleAsync|0>d.MoveNext()
17:02:47 <CbTest> --- End of stack trace from previous location ---
17:02:47 <CbTest>    at GravyBot.MessageQueueService.<>c__DisplayClass12_0`1.<<ApplyRules>g__ExecuteRuleAsync|0>d.MoveNext()
```

thanks for any assistance on this.

Thanks!

**Comment by huoyaoyuan** [comment]
I've heard pixiv side change happened recently, but didn't investigate it because my saved refresh token still works. I'll look at this later.

**Comment by huoyaoyuan** [comment]
@halomademeapc  I've pushed an updated login method to master.
Unfortunately, login with password is now abandoned by Pixiv. The new method must incorporate with a browser or webview. You can save the refresh token. It's valid in long term.

**Comment by halomakes** [comment]
Thanks, I obtained a refreshtoken and updated my code to use that instead. Can you add an ObsoleteAttribute to the overload that accepts username/password for posterity?

**Comment by huoyaoyuan** [comment]
Yes. I've already added `Obsolete` in latest version.
